### ISSUE TITLE
Proto documentation needed

### ISSUE THREAD

**Issue by itsMeDavidV** [teslamotors/vehicle-command#103]
Just wanted to get a heads up on when we can expect documentation for using the Proto files directly?

I know that protos just came out last week, however given the timeline to deprecation of reg commands and given that a lot of vehicles now only accept signed commands is important to get this documentation available to developers as soon as possible, especially those who have 3rd party apps with large existing user-base/fleet.

**Comment by itsMeDavidV** [comment]
Any update to this?

**Comment by sethterashima** [comment]
Draft is in internal review.

**Comment by Urkman** [comment]
Any updates @sethterashima ?

**Comment by sethterashima** [comment]
Protocol spec added in https://github.com/teslamotors/vehicle-command/pull/142. Feedback is welcome.
