### ISSUE TITLE
Ability to edit redirect_uri / redirect_url

### ISSUE THREAD

**Issue by vbarrier** [teslamotors/vehicle-command#11]
Hi

I didn’t found any way to edit app settings from the developer.tesla.com website

I would like to add a localhost url or the default one from postman to test oauth: https://oauth.pstmn.io/v1/browser-callback

**Comment by andig** [comment]
Currently no way to do so. Quickly setting up a test environment, that's an absolute show stopper.

**Comment by andig** [comment]
ping @teslamotors this is an absolute show-stopper.

**Comment by andig** [comment]
Friendly ping @teslamotors @tesla-sdk-publish there are already >20 upvotes. Is there any chance to get this addressed short-term? We'd need to double- and triple-register otherwise for testing and production changes would not be possible.

**Comment by JSpiner** [comment]
If it is difficult to implement an edit function, how about creating a delete function first? Currently, tesla developer console can only create two apps, so it is difficult to test them anymore.

**Comment by aaronpkahn** [comment]
We'll be adding the ability to edit redirect_uri, return_url, and allowed_origins in the coming weeks.  Sorry for the lame inconvenience/blocker.

**Comment by rawmean** [comment]
> We'll be adding the ability to edit redirect_uri, return_url, and allowed_origins in the coming weeks. Sorry for the lame inconvenience/blocker.

Is it also possible to allow editing scope? Users will be prompted to approve/deny the new scope.
If one forgets to add a scope a new domain needs to be acquired and registered and a new https certificate needs to be acquired and it's a huge hassle. Not to mention that users need to re-log in.

Thanks

**Comment by grantmac** [comment]
Any timeline on this @aaronpkahn ?

**Comment by grantmac** [comment]
It also looks like you cannot register more than 5 apps...

**Comment by JSpiner** [comment]
@grantmac yes it is. So I created an additional new account.
Sadly this is the only solution.

**Comment by jbanyer** [comment]
This appears to be possible now. I just edited the redirect URLs for an existing app.

**Comment by Kelex60fps** [comment]
How can I create a redirect link pls

**Comment by ThomasAlxDmy** [comment]
Yup you can do it now via the UI.

**Comment by andig** [comment]
Plus: you can even changes scopes now 👍🏻
