### ISSUE TITLE
Elliptic ScalarMult function availability in other languages

### ISSUE THREAD

**Issue by joshendy** [teslamotors/vehicle-command#117]
Sorry, this isn't exactly on topic - I'm just desperate. I've been trying to convert this library to Java so I can natively run this on Android. I'm stuck on the elliptic.P256().ScalarMult function. I can't find an equivalent elliptic P256 scalar multiply function in bouncy castle or any other crypto library. Any help or direction to go looking in would be greatly appreciated.

**Comment by RonnyWinkler** [comment]
Hi @joshendy 
Could you perhaps share your Java version? I try to implement the signed command in JJ (NodeJS) and can't find what's really needed to build the correct base64 body. Many thanks :-)

**Comment by joshendy** [comment]
Whoops. Bouncy castle's default ECMultiplier works fine as a replacement.
