### ISSUE TITLE
Error: Client / Secret ID combination Error. Please help. Thank you. 

### ISSUE THREAD

**Issue by onlyusedtesla** [teslamotors/vehicle-command#134]
We tried generating the partner token, and triple checked the client/secret ID combination, and we cannot get past this error.

{
    "error": "unauthorized_client",
    "error_description": "We don't recognize this client_id and client_secret combination",
    "error_uri": "https://auth.tesla.com/error/reference/96879f65-4f18-4f1c-ab97-4bce6265cc8a-1704326384901"
}
<img width="742" alt="Screenshot 2024-01-05 at 9 30 43 AM" src="https://github.com/teslamotors/vehicle-command/assets/89537447/b0a30554-65c8-4ca4-9927-0eca7ae42fec">

**Comment by stephanmo** [comment]
The problem I also face is, that my application registration(s) have vanished in my developer account.
Also creating a new application fails.
When trying to create a new application, i get a success message, but i cannot find the application anywhere respectively i do not get redirected after successful creation.

**Comment by techguy993** [comment]
Yes, I am having the same problem, though my Tesla developer account shows my client_id and client_secret, so not sure what is wrong.

**Comment by onlyusedtesla** [comment]
I got new numbers / client / id / secret and same error.

**Comment by jdolderer** [comment]
Same issue here. Any help welcome!

**Comment by onlyusedtesla** [comment]
even our new numbers didn't work. Can someone please help here?

**Comment by hauserkristof** [comment]
I have the same problem, with a newly created app. Fortunately old ones work well.

**Comment by onlyusedtesla** [comment]
I wish someone at Tesla would get back to us / fix this or turn on billing so we can build our application. This is blocking us. Please tesla engineering help us. Thank you

**Comment by techguy993** [comment]
Tesla Engineering?  Any Help Please?????

**Comment by gilhrpenner** [comment]
Also having the same issue, posting here for viz and subscribing.

**Comment by onlyusedtesla** [comment]
Tesla engineering please get back to us about this. Everyone is blocked. Thank you. Its been 2 weeks now.

**Comment by ThomasAlxDmy** [comment]
Hey all - have you tried setting `Content-Type: application/x-www-form-urlencoded` ?

**Comment by gilhrpenner** [comment]
> Hey all - have you tried setting the header `Content-Type: application/x-www-form-urlencoded` ?

Yep, below is the curl from my postman, but have also tried with the curl provided in the docs.

```
curl --request POST \
  --url 'https://auth.tesla.com/oauth2/v3/token?grant_type=client_credentials&client_id=[client_id]&client_secret=[client_secret]&scope=openid%20offline_access%20user_data%20vehicle_device_data%20vehicle_cmds&audience=https%3A%2F%2Ffleet-api.prd.na.vn.cloud.tesla.com' \
  --header 'Content-Type: application/x-www-form-urlencoded'
```

**Comment by techguy993** [comment]
yes tried that...here is the curl command

curl --request POST \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'grant_type=client_credentials' \
  --data-urlencode "client_id=$CLIENT_ID" \
  --data-urlencode "client_secret=$CLIENT_SECRET" \
  --data-urlencode 'scope=openid vehicle_device_data vehicle_cmds vehicle_charging_cmds' \
  --data-urlencode "audience=$AUDIENCE" \
  'https://auth.tesla.com/oauth2/v3/token'

**Comment by gilhrpenner** [comment]
@onlyusedtesla  why has this marked as closed? Did you figure out what was the issue??

**Comment by onlyusedtesla** [comment]
It started working for us.

**Comment by gilhrpenner** [comment]
> It started working for us.

Did you do anything different? Did you regen your client id and secret or changed anything else?

**Comment by onlyusedtesla** [comment]
I work with a partner he's the dev. He told me. I will ask him and get back to you. I do mostly sales. He said tesla updated the backend too and he used the recommendation from @ThomasAlxDmy so it started working.

**Comment by gilhrpenner** [comment]
> I work with a partner he's the dev. He told me. I will ask him and get back to you. I do mostly sales. He said tesla updated the backend too and he used the recommendation from @ThomasAlxDmy so it started working.

Do you mind re-opening this issue as some other people are still having issues with it?

**Comment by onlyusedtesla** [comment]
done. 
@gilhrpenner

**Comment by jdolderer** [comment]
I was using headers before, which doesn't work.

Using it like this works:

```curl --request POST \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'grant_type=authorization_code' \
  --data-urlencode "client_id=$CLIENT_ID" \
  --data-urlencode "client_secret=$CLIENT_SECRET" \
  --data-urlencode "code=$CODE" \
  --data-urlencode "audience=$AUDIENCE" \
  --data-urlencode "redirect_uri=$CALLBACK" \
  'https://auth.tesla.com/oauth2/v3/token'
  ```
  
  See [documentation](https://developer.tesla.com/docs/fleet-api#authentication)

**Comment by gilhrpenner** [comment]
> I was using headers before, which doesn't work.
> 
> Using it like this works:
> 
> ```
>   --header 'Content-Type: application/x-www-form-urlencoded' \
>   --data-urlencode 'grant_type=authorization_code' \
>   --data-urlencode "client_id=$CLIENT_ID" \
>   --data-urlencode "client_secret=$CLIENT_SECRET" \
>   --data-urlencode "code=$CODE" \
>   --data-urlencode "audience=$AUDIENCE" \
>   --data-urlencode "redirect_uri=$CALLBACK" \
>   'https://auth.tesla.com/oauth2/v3/token'
> ```
> 
> See [documentation](https://developer.tesla.com/docs/fleet-api#authentication)

Can confirm this is working now.

**Comment by techguy993** [comment]
This is the authorization code request type. The above post in posted is the client credentials request type which does not work. Do you have an example of that request type?

**Comment by firefixmaarten** [comment]
+1,
I also get the error when trying to request partner token...
```
# Partner authentication token request
curl --request POST \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'grant_type=client_credentials' \
  --data-urlencode "client_id=$CLIENT_ID" \
  --data-urlencode "client_secret=$CLIENT_SECRET" \
  --data-urlencode 'scope=openid vehicle_device_data vehicle_cmds vehicle_charging_cmds' \
  --data-urlencode "audience=$AUDIENCE" \
  'https://auth.tesla.com/oauth2/v3/token'
```
gives:
{"error":"invalid_request","error_description":"Invalid resource","error_uri":"https://auth.tesla.com/error/reference/02aacff7-1399-4ce9-bb88-d0f26d480e66-1706258213930"}%                                                                                                                                                                   

To bad the reference does not work...

**Comment by gilhrpenner** [comment]
> +1, I also get the error when trying to request partner token...
> 
> ```
> # Partner authentication token request
> curl --request POST \
>   --header 'Content-Type: application/x-www-form-urlencoded' \
>   --data-urlencode 'grant_type=client_credentials' \
>   --data-urlencode "client_id=$CLIENT_ID" \
>   --data-urlencode "client_secret=$CLIENT_SECRET" \
>   --data-urlencode 'scope=openid vehicle_device_data vehicle_cmds vehicle_charging_cmds' \
>   --data-urlencode "audience=$AUDIENCE" \
>   'https://auth.tesla.com/oauth2/v3/token'
> ```
> 
> gives: {"error":"invalid_request","error_description":"Invalid resource","error_uri":"[https://auth.tesla.com/error/reference/02aacff7-1399-4ce9-bb88-d0f26d480e66-1706258213930"}%](https://auth.tesla.com/error/reference/02aacff7-1399-4ce9-bb88-d0f26d480e66-1706258213930%22%7D%)
> 
> To bad the reference does not work...

With this request I am getting

{"error":"invalid_scope","error_description":"The client is not allowed to access the requested resource.","error_uri":"https://auth.tesla.com/error/reference/d3260b15-4d24-4610-a002-e462e7d180f9-1706315679547"}

**Comment by ogudet** [comment]
Hello, does someone has made progress to resolve this issue ?
I'm facing the same error: "error_description": "We don't recognize this client_id and client_secret combination"

**Comment by ogudet** [comment]
fond there https://documenter.getpostman.com/view/781424/2s9YRCWB4f#6da852b2-ca25-4d62-b268-fb20384abee0
some node.js code where with the same data as the curl the request is successful.....

**Comment by gilhrpenner** [comment]
> fond there https://documenter.getpostman.com/view/781424/2s9YRCWB4f#6da852b2-ca25-4d62-b268-fb20384abee0 some node.js code where with the same data as the curl the request is successful.....

[Shankar's Blog](https://shankarkumarasamy.blog/) is on point and the steps they added for the postman is great. Thanks for this link!!

**Comment by ymerdrengene** [comment]
I get the same issue

`{
    "error": "unauthorized_client",
    "error_description": "We don't recognize this client_id and client_secret combination",
    "referenceID": "32705617-9612..."
}`

**Comment by techguy993** [comment]
Still doesn't work....

{
  "error": "unauthorized_client",
  "error_description": "We don't recognize this client_id and client_secret combination",
  "referenceID": "f1fa785f-08cb............
}

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is being narrowed to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
