### ISSUE TITLE
Feature Request: Support linux devices as key

### ISSUE THREAD

**Issue by rcasta74** [teslamotors/vehicle-command#147]
I'm using linux phone and no app is available for it, so I miss this feature.

**Comment by sethterashima** [comment]
Out of scope for this project. Third parties are welcome to use the SDK and protocol specification to develop new apps.

**Comment by rcasta74** [comment]
I'm not interested in a full app, but in a command that will let me use a linux phone as a key.
If I understand this [post](https://github.com/teslamotors/vehicle-command/issues/191#issuecomment-1955236676_) correctly, it is planned to make it possible to send `drive` command over BLE: that would be enough for me.
