### ISSUE TITLE
Fleet API Auth Customer Error

### ISSUE THREAD

**Issue by jaggerc** [teslamotors/vehicle-command#153]
Is anyone getting 'Auth Customer Error' when trying to refresh a token.  We are receiving it on about 10% of users that have switched over to the fleet api.  They have not reset their password or done anything to change the authentication after they authenticated.  Not sure what is going on.

**Comment by stebo1970** [comment]
Ich bekomme diesen Fehler:

_Tokenerzeugung fehlgeschlagen

insufficient scopes: missing token scopes: [user_data]_

Jemand eine Idee was ich tun kann?

**Comment by andig** [comment]
@stebo1970 your question doesn't have anything to do with this repo and is OT.

**Comment by jaggerc** [comment]
Duplicate

**Comment by stebo1970** [comment]
> @stebo1970 your question doesn't have anything to do with this repo and is OT.

sorry!
