### ISSUE TITLE
Vehicle Endpoints work perfectly, but Vehicle Commands return Method not Allowed (on HTTP Proxy)

### ISSUE THREAD

**Issue by fktc** [teslamotors/vehicle-command#157]
I've successfully set up a tesla developer account and an applications with all required scopes. Afterwards I've followed the instructions to set up the http proxy & also paired a vehicle.

Vehicle Endpoints work perfectly (e.g. `GET /api/1/vehicles/{vehicle_tag}/vehicle_data`)
However, all vehicle commands like `flash_lights` or `door_unlock` fail with error 

```
{
  "response": null,
  "error": "Method Not Allowed",
  "error_description": ""
}
```

I'm using the following command:
```
        curl --cacert cert.pem \
    --header 'Content-Type: application/json' \
    --header "Authorization: Bearer <myToken>" \
    "https://localhost:4443/api/1/vehicles/<myVin>/door_unlock" \
    | jq -r .
```

**Comment by eclipsed4utoo** [comment]
Seems like you are trying to do a GET instead of a POST. The vehicle command APIs are POST, not GET. I believe curl does a GET by default if you don't give it an http method.
