### ISSUE TITLE
Error when registering endpoint in North America, works fine in EU.

### ISSUE THREAD

**Issue by vagh141** [teslamotors/vehicle-command#162]
Based on some Github discussions we have found out that we should call the /register endpoint (https://developer.tesla.com/docs/fleet-api#register) for both eu (https://fleet-api.prd.eu.vn.cloud.tesla.com/) and na (https://fleet-api.prd.na.vn.cloud.tesla.com/). When trying to call eu endpoint it works just fine, however when calling na endpoint we get this error message:

![Skjermbilde 2024-02-03 kl  14 23 24](https://github.com/teslamotors/vehicle-command/assets/123909004/6149ed04-1ee1-4354-bdca-d683ada09342)

We are located in Norway and the account is also registered there.

**Comment by vagh141** [comment]
The reason we want to register in NA, is because when we try to send a command to a car in NA we get the error: "vehicle rejected request: your public key has not been paired with the vehicle", however in the EU it works just fine. We also have this from the internal tool. 
![IMG_3518](https://github.com/teslamotors/vehicle-command/assets/123909004/9174f9b9-69a2-43ee-bd6e-2582d7c5c099)

**Comment by zerocooling** [comment]
> internal tool.

How can you see this homepage ?
I couldnt find it, even I have tried few hours.
