### ISSUE TITLE
[Request] Allow users to edit third party access instead of forcing them to reset

### ISSUE THREAD

**Issue by itsMeDavidV** [teslamotors/vehicle-command#167]
I apologize in advance as this is not directly related to vehicle-command, however **I wanted to request that Tesla 3rd party app access be editable instead of only offering the revoke action** 

Because revoke is the only option, it forces the user to have to sign out of 3PA -> revoke access -> sign in to 3PA just to edit access. While we try our best to coach and educate users on these steps, many still ultimately face a lot of friction and frustration here and I think making access editable would greatly improve the experience for those users.

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is being narrowed to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
