### ISSUE TITLE
Varying results when trying to add BLE key

### ISSUE THREAD

**Issue by vagh141** [teslamotors/vehicle-command#168]
When adding a the public.pem file to the car with ble, it sometimes works, and sometimes returns this error:
Error: failed to find BLE beacon for VIN (): can't scan: context deadline exceeded

The command is sent with terminal on Mac with this command:
./tesla-control -vin VIN -ble add-key-request public.pem owner cloud_key

Im sitting in the car, so range should not be an issue.

**Comment by sheng168** [comment]
this has been reliable for me from Apple Watch and iPhone

**Comment by sethterashima** [comment]
Closing this ticket, but feel free to re-open if you're able to confirm permissions are correct and can still reproduce.
