### ISSUE TITLE
Native apps using fleet API are forced to expose Client secret - how to avoid?

### ISSUE THREAD

**Issue by g-mocken** [teslamotors/vehicle-command#170]
If I am not mistaken, the fleet API closely follows https://datatracker.ietf.org/doc/html/rfc6749#section-4.1, which by itself is fine.
However when using this scheme for implementing a native app (e.g. iOS), the app must contain and transmit the client secret, making it easy to extract or intercept it (see https://datatracker.ietf.org/doc/html/rfc8252#section-8.5). The RFC explicitly mentions the risk of client impersonation.

So what is the recommended way for implementing a native app using the current fleet API (if there is any), or will the fleet API be extended to securely support native apps?

**Comment by sethterashima** [comment]
We plan on extending the Fleet API to support native apps. [Stay tuned](https://developer.tesla.com/docs/fleet-api#announcements-amp-api-changelog).

**Comment by peter-tab** [comment]
> We plan on extending the Fleet API to support native apps. [Stay tuned](https://developer.tesla.com/docs/fleet-api#announcements-amp-api-changelog).

Great. Adding PKCE would further improve security… 😉

**Comment by jonasman** [comment]
@sethterashima just for planning purposes.
Is this a new SDK that you are preparing or just a universal/deep link to open the official Tesla app to create the new token?

**Comment by g-mocken** [comment]
I have just noticed a recent update on the issue: 
https://developer.tesla.com/docs/fleet-api#2024-07-08-open-source-support
https://developer.tesla.com/docs/fleet-api#open-source-token

**Comment by jbanyer** [comment]
The new changes for [open-source tokens](https://developer.tesla.com/docs/fleet-api#open-source-token) appear to provide a solution for obtaining API tokens. But what about command signing? That would still require access to a private key corresponding to a public key installed on the vehicle.

**Comment by sethterashima** [comment]
> But what about command signing? That would still require access to a private key corresponding to a public key installed on the vehicle.

The app should generate its own key pair the first time it runs, and use https://pkg.go.dev/github.com/teslamotors/vehicle-command@v0.0.2/pkg/vehicle#Vehicle.SendAddKeyRequest.

**Comment by g-mocken** [comment]
I do not see the "open-source token" anymore in the documentation (only in web archive for mid 2024). Has this feature been revoked again?
