### ISSUE TITLE
Does bluetooth work for changing amps?

### ISSUE THREAD

**Issue by ASomerN** [teslamotors/vehicle-command#177]
As per title. Are all the api endpoints available using Bluetooth? I'm specifically interested in the amp changing using Bluetooth.

**Comment by sethterashima** [comment]
Yes, for example: `tesla-control -ble charging-set-amps 20`

See [the tesla-control README file](https://github.com/teslamotors/vehicle-command/blob/main/cmd/tesla-control/README.md) for instructions on pairing a key. The [BLE example program](https://github.com/teslamotors/vehicle-command/blob/main/examples/ble/main.go) may also be helpful.
