### ISSUE TITLE
[Question] API for alerts sentry

### ISSUE THREAD

**Issue by MagoKimbra** [teslamotors/vehicle-command#179]
Hi, sorry for the question, is there an api that warns that there has been a sentry event?
I'm trying to make an app on raspberry PI that warns me when the sentry records something around the car. I can't find any command in the documentation that does this.
Thank's for response.

**Comment by sethterashima** [comment]
There's not currently an API for this.

**Comment by MagoKimbra** [comment]
Thank's!!
