### ISSUE TITLE
Refreshing a token from DigitialOcean gives a 403

### ISSUE THREAD

**Issue by Urkman** [teslamotors/vehicle-command#180]
When I refresh a token from my MacBook everything is fine.
But from my DigitalOcean server I get a 403.

Why?

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is being narrowed to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
