### ISSUE TITLE
Energy History endpoint shows incorrect grid import/export for multi-powerwall setups

### ISSUE THREAD

**Issue by rustyshelf** [teslamotors/vehicle-command#184]
Calling `GET /api/1/energy_sites/{energy_site_id}/calendar_history?kind=energy&period=day...` returns a daily summary for the period requested. The house use and solar generated seem to match the Tesla app reliably, which is great. 

However the grid import/export values seems wrong. If we calculate them as:
import: `battery_energy_imported_from_grid` + `consumer_energy_imported_from_grid`
export: `grid_energy_exported_from_battery` + `grid_energy_exported_from_solar` + `grid_energy_exported_from_generator`

For installations with a single Powerwall these values seem to match what's in the Tesla app. For multi-Powerwall sites however the value of import and export seems to grow during the day. For example say 0.1kW has been imported and exported from a site for a given day (eg: barely any grid use) the API will often report these values as much higher, say 9kWh for each. Is there something else I need to be taking into account here for sites that have more than one Powerwall?

Interestingly at my site (which has 3 Powerwalls) for a while the Tesla app used to show this same incorrect data, however it was fixed a month or two ago, I'm just not sure how?

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is being narrowed to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
