### ISSUE TITLE
Access VIN over BLE

### ISSUE THREAD

**Issue by sheng168** [teslamotors/vehicle-command#192]
I working on a stand-alone Apple Watch Bluetooth app. I can add my public key to the vehicle, but the VIN is needed to execute commands and I've found no place to retrieve it. It's not very user friendly to ask user to enter 17 characters of letters and numbers. Is there a better way?

**Comment by sheng168** [comment]
I'm putting VIN in vehicle name during the inital setup as a temporary workaround

**Comment by rileymd88** [comment]
The following vehicle endpoint will give you a list of vehicles and include
the VIN: api/1/vehicles

**Comment by sheng168** [comment]
I'm trying to make an app that works when there's no cellular nor wifi; using just BLE

**Comment by Whirlwind** [comment]
I have same problem. There's no cellular nor wifi, too. :)

**Comment by sheng168** [comment]
I ask the user to add their VIN in the car's name
