### ISSUE TITLE
Feature Request: Endpoint to access upgrade/premium connectivity invoices

### ISSUE THREAD

**Issue by sapkra** [teslamotors/vehicle-command#198]
Currently we can only get the invoices for charging but it would be great to also have an endpoint to get all invoices for all software upgrades.

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is being narrowed to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
