### ISSUE TITLE
 error: "description": "{\"response\":null,\"error\":\"Unauthorized missing scopes\",\"error_description\":\"\"}",

### ISSUE THREAD

**Issue by onlyusedtesla** [teslamotors/vehicle-command#199]
"description": "{\"response\":null,\"error\":\"Unauthorized missing scopes\",\"error_description\":\"\"}", (edited) 

We are sending scopes in our auth request so not sure what’s going on here  

Thank you.

**Comment by robin-karlsson** [comment]
We see that sometimes as well, usually indicates that the end user didn't approve of the requested scopes needed for the issued request.

**Comment by ThomasAlxDmy** [comment]
That's right. We've made docs changes to reflect missing scopes: https://developer.tesla.com/docs/fleet-api#faq & https://developer.tesla.com/docs/fleet-api#authorization-scopes
