### ISSUE TITLE
fleet_status returns 404 for Driver accounts

### ISSUE THREAD

**Issue by efriesner** [teslamotors/vehicle-command#204]
Given that vehicles on a Driver account can be have a public key, I would expect this API to return data instead of 404 for these vehicles.

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is being narrowed to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
