### ISSUE TITLE
App not recognized anymore

### ISSUE THREAD

**Issue by vbarrier** [teslamotors/vehicle-command#21]
I'm trying to get a new partner token (it worked before)

and now I'm getting: 

```
{
    "error": "unauthorized_client",
    "error_description": "We don't recognize this client_id and client_secret combination",
    "error_uri": "https://auth.tesla.com/error/reference/9c0edd7f-ca24-49ab-a2e9-cab13cbb7ee1-1698135037237"
}

```
I'm still able to get Third-party token also but when I try to use it: 

```
{
    "error": "Account 44288eadbe21-4660-9816-88452a983f3b must be registered please see https://developer.tesla.com/docs/fleet-api#register"
}
```

**Comment by Darko** [comment]
Make sure to register on both the NA and EU regions. If you've done it only on one of them, you won't be able to create and use tokens for other regions. So just register for all regions.

**Comment by vbarrier** [comment]
Thank you for your reply.

How do I register on both? Should I create 2 apps?

**Comment by Darko** [comment]
With the same app client id and secret, make a request to the dedicated region api for registration. For example if you did a POST to NA:
`POST https://fleet-api.prd.na.vn.cloud.tesla.com/api/1/partner_accounts`
send a post request to EU api as well
`POST https://fleet-api.prd.eu.vn.cloud.tesla.com/api/1/partner_accounts`
