### ISSUE TITLE
Unable to share vehicle

### ISSUE THREAD

**Issue by NikhilTank35** [teslamotors/vehicle-command#214]
When the vehicle owner scans https://www.tesla.com/_ak/app.stage.emulate.network, it gives "Unable to share vehicle, this third party is not registered with Tesla......" error even after registering it but https://www.tesla.com/_ak/blinded-standard.000webhostapp.com works which have same public key present.

<img src="https://github.com/teslamotors/vehicle-command/assets/41949926/941f273c-f353-4085-88ee-3bf847462fc0" width="40%"> 

![Screenshot from 2024-03-13 19-29-11](https://github.com/teslamotors/vehicle-command/assets/41949926/1dad7537-4731-44f2-be7f-687b949d7c74)

same with https://www.tesla.com/_ak/app.emulate.network

**Comment by NikhilTank35** [comment]
@ThomasAlxDmy @sethterashima @fabianhu Can you please help us with this?

**Comment by NikhilTank35** [comment]
Is it like only the `*.com` domain works ?

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is being narrowed to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
