### ISSUE TITLE
How to use set_pin_to_drive with a Tesla for Business owner account?

### ISSUE THREAD

**Issue by vbarrier** [teslamotors/vehicle-command#223]
Hi, 

I'm trying to be able to set : set_pin_to_drive for a vehicles that are owned by a Tesla for Business account. If I use an access token from a listed driver => I'm not allowed, not enough privileges.

But the vehicle doesn't have any "owner" tesla account except the Tesla for Business one. If I get an access for that account, it's doesn't have any listed vehicle so set_pin_to_drive return not_found.

So no way to use the set_pin_to_drive in that case?

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is limited to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
