### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by deece** [teslamotors/vehicle-command#225]
Could we please have a docker image for this? It would make deployment much easier.

**Comment by rileymd88** [comment]
I created a Dockerfile here which works:
https://github.com/rileymd88/vehicle-command/blob/main/Dockerfile

**Comment by llamafilm** [comment]
Here’s a Home Assistant addon: https://github.com/llamafilm/tesla-http-proxy-addon

**Comment by RonnyWinkler** [comment]
A docker.io image would be nice, too, to use it directly in container environments with dockerhub integration :-)

**Comment by kiler129** [comment]
Given the security implications, I think Tesla should provide an officially maintained container image.

**Comment by agbpatro** [comment]
you can use https://hub.docker.com/r/tesla/vehicle-command/tags to download official image
