### ISSUE TITLE
Unable to register with localhost

### ISSUE THREAD

**Issue by llamafilm** [teslamotors/vehicle-command#227]
I tried registering using localhost for testing, but it doesn't work.  The error shown in this screenshot suggests that this should be possible.  I get the same error with either `localhost` or `127.0.0.1`.

<img width="689" alt="image" src="https://github.com/teslamotors/vehicle-command/assets/3991046/3d55b5a1-9b58-4ac2-a95b-3af8b517fb8b">

**Comment by sethterashima** [comment]
Please see https://developer.tesla.com/docs/fleet-api#help-and-support.

In order to improve our response times, the scope of the Github issues tracker is limited to the Golang code in the SDK. Backend issues should be reported to the Fleet API support team.
