### ISSUE TITLE
How to decrypt the vehicle_data

### ISSUE THREAD

**Issue by stephenml** [teslamotors/vehicle-command#234]
The `vehicle_data` returned by the API endpoint `/api/1/vehicles/{vehicle_tag}/vehicle_data` when passed with the parameter `endpoints=vehicle_data_combo` appears to be a base64-encoded string. However, after decrypting it, the resulting data appears to be garbled.

**Comment by sethterashima** [comment]
The data field is a protobuf that mostly overlaps with the JSON data. There's a good chance this is getting refactored, so I would recommend against relying on it and don't want to release code that will encourage clients to do so.
