### ISSUE TITLE
Server returned 429: Too Many Requests: Retry later (hidden by tesla-command)

### ISSUE THREAD

**Issue by fabianhu** [teslamotors/vehicle-command#238]
Hi,
I try to solar-charge my Tesla 
- in fact it was working beautifully for months now. 
But now I get the above error.
It seems, that if the weather is a little cloudy, the amount of 50 requests gets eaten away really fast. 
Is there any plan to lift this limitation?

But now for the software part:
tesla-command hides the fact of "Too Many Requests: Retry later" and only gives "Error: context deadline exceeded".
While doing so, it produces 10 retries to the server (where I don't know, if these are also counted by the server)

Please advise, how the retry can be avoided and how the result of 429 can be obtained without parsing the -debug output.
Is there any way to know, how many requests are left?

Many thanks!

PS: using the tesla-command for my python [implementation](https://github.com/fabianhu/tesla_api).

**Comment by sethterashima** [comment]
I'll look into the 429.

Have you looked into sending solar charging commands over BLE to avoid command limits?

**Comment by fabianhu** [comment]
Thanks, I eyeballed the BLE, but my Pi would have to move near the garage. Wifi is great there, but the Pi is at the other side wired to the heating system. Or I would have to make a relay-Pi.  An interface over Wifi directly would also be nice - but this is car stuff and out of scope here.

**Comment by sreuter** [comment]
Tesla just recently started to enforce their (pretty low) rate limits. I left another comment regarding the situation here: https://github.com/alandtse/tesla/issues/961 .. It likely created big trouble for most of their consumers tbh, as they also didn't communicate enforcement beforehand.

**Comment by fabianhu** [comment]
Mentioning #52 here, It would be nice to get some data over the BLE interface. I can see the car by pinging it over BLE, but I don't know connection or SOC. Any help is appreciated. 
PS: I just got my relay-Pi.

**Comment by fabianhu** [comment]
Did another test today via the API: The 429 appears on the 17th command sent to the vehicle this day. 
Does the tesla-command send multiple requests with one call and they are all counted?

-> Looking at the debug output: Yes it does send 3! 
1. Requesting session info from DOMAIN_INFOTAINMENT
2. Requesting session info from DOMAIN_VEHICLE_SECURITY
3. and the actual command 
== 3
50/3 = 16.6 -> the 17th command does not get through.

Is there a way to send a command "one shot"?

Unfortunately the tesla-command does not provide any output about the "retry after" value in minutes, even in Debug.

I would still opt for a WiFi interface locally. Just use the same stack and auth like the fleet API on a local port.
