### ISSUE TITLE
Why does registration always fail? 

### ISSUE THREAD

**Issue by doordiey** [teslamotors/vehicle-command#240]
This error code keeps returning when I register the app. What does this error code mean?
TSLA_ACM_EXCP_4219
![20240517111204](https://github.com/teslamotors/vehicle-command/assets/32118370/e8a14ce3-c6ca-4975-84c0-96bd733178cf)

**Comment by sethterashima** [comment]
The scope of this issue tracker is limited to the Golang code in the SDK. Please see https://developer.tesla.com/docs/fleet-api#help-and-support.
