### ISSUE TITLE
Document the session cache mechanism and file

### ISSUE THREAD

**Issue by jbanyer** [teslamotors/vehicle-command#246]
Can we get a few notes added to the README about the session cache and file? The README describes the TESLA_CACHE_FILE option and that:
> The cache allows programs to skip sending handshake messages to a vehicle.

This seems like a desirable thing. Can we get a bit more info? Eg is it best practice to use a cache file? Does the cache impact transaction rate limits?

Thanks!

**Comment by sethterashima** [comment]
@jbanyer please feel free to comment on the linked PR if something is unclear.

**Comment by jbanyer** [comment]
Perfect, thanks @sethterashima
