### ISSUE TITLE
impossible to wake up the car with BLE

### ISSUE THREAD

**Issue by kurb77** [teslamotors/vehicle-command#248]
hello,
i have a problem to wake up my car with BLE, all other command work well, but when a try to wake up the car a have this error

`Error: context deadline exceeded`

my command line:
`./tesla-control -ble -vin XP7YGCEL1NB009999 -key-file private.pem wake`

when I used the 'wake' command through http (before the limitations on the number of calls) it worked correctly  

thank you

**Comment by erikgieseler** [comment]
Try the command `./tesla-control -ble -domain vcsec -vin XP7YGCEL1NB009999 -key-file private.pem wake`

**Comment by kurb77** [comment]
it work, thank you
