### ISSUE TITLE
Can't register public key, get error "Validation failed: Csr is not a valid CSR"

### ISSUE THREAD

**Issue by teckel12** [teslamotors/vehicle-command#251]
Following the readme instructions:

1. `export TESLA_KEY_NAME=$(whoami)`
2. `tesla-keygen create > public_key.pem`
3. Create file: `https://<app domain>/.well-known/appspecific/com.tesla.3p.public-key.pem`
4. Copy contents of `public_key.pem` to `com.tesla.3p.public-key.pem`
5. Create token with `https://auth.tesla.com/oauth2/v3/token`
6. Attempt to register with `https://fleet-api.prd.na.vn.cloud.tesla.com/api/1/partner_accounts` including token

   1. It accepts the token
   2. Loads the `com.tesla.3p.public-key.pem` file
   3. But returns the error `Validation failed: Csr is not a valid CSR`

**Comment by elafontaine** [comment]
Thank you so much for this comment ! this is also what I was stuck on!
