### ISSUE TITLE
Charging history for non-supercharging

### ISSUE THREAD

**Issue by rawmean** [teslamotors/vehicle-command#262]
Charging history endpoint seem to have changed recently to this:
https://developer.tesla.com/docs/fleet-api#charging_history

But this only returns the supercharging records. How can we get the records for non-supercharging?

**Comment by sethterashima** [comment]
This scope of this issue tracker is limited to the Golang code in this repository. Please reach out to the Fleet API support team: https://developer.tesla.com/docs/fleet-api#help-and-support.
