### ISSUE TITLE
Do you need to have your own website hosted to consume Tesla Fleet API?

### ISSUE THREAD

**Issue by jenildesai25** [teslamotors/vehicle-command#274]
I have been banging my head for couple hours to figure out how Tesla Fleet API works, I don't know why Tesla had made it so difficult to use it. Nevertheless, could someone tell me if I need to host a website to receive partner account key?. I don't have website I was looking to play with my car using this commands and was wondering if I can just use Tesla Fleet API without hosting a website. Any help is appreciated, Thank you

**Comment by sethterashima** [comment]
You can enter `http://localhost:<port number>` for allowed origin when registering.

However, you will not be able to provide an `https://tesla.com/_ak/<your domain>` link that would allow your users to enroll your virtual key onto their cars.

**Comment by Andreas-lang** [comment]
I built a simple website on Vercel to stay flexible. Vercel was its own learning curve, but very useful, fast and stable.
