### ISSUE TITLE
How to solve the MESSAGEFAULT_ERROR_RESPONSE_MTU_EXCEEDED

### ISSUE THREAD

**Issue by Whirlwind** [teslamotors/vehicle-command#279]
I got a error `MESSAGEFAULT_ERROR_RESPONSE_MTU_EXCEEDED` when I connect the vehicle by BLE in my ios app.

It seems that the response data too large.

I check the Apple document, ios disallow app change the mtu. How to solve it?

**Comment by sethterashima** [comment]
The limiting factor for the MTU is VSCEC RAM, so the MTU is determined by the vehicle.

What command are you using that results in MTU errors?

**Comment by Whirlwind** [comment]
@sethterashima I am fetch the vehicle data by BLE:
```
Action.VehicleAction.GetVehicleData.GetVehicleState
```
It seams that the data is too large, and the INFOTAINMENT do not split the message.
