### ISSUE TITLE
Unable to add-key with fleet's key

### ISSUE THREAD

**Issue by programmrz** [teslamotors/vehicle-command#282]
I first installed the fleet key with /_ak/ and it shows up in list-key as ***fa56	ROLE_FM    KEY_FORM_FACTOR_UNKNOWN

I then use the private key to whitelist a newly created public key to send to the vehicle with ./tesla-control -debug -key-file private_telsa.pem add-key public.pem driver ios_device 

The client public key matches what /api/1/partner_accounts/public_key returns. 

I get a "Failed to execute command: MESSAGEFAULT_ERROR_INSUFFICIENT_PRIVILEGES" error message as a result. 

My intent is to generate keys on the backend and then pass them to clients on an as needed basis... is this not possible?

Is there a way to whitelist a driver key with oauth token instead?

**Comment by sethterashima** [comment]
See the Fleet Manager entry under https://github.com/teslamotors/vehicle-command/blob/main/pkg/protocol/protocol.md#roles.
