### ISSUE TITLE
Cannot trigger Guest Mode

### ISSUE THREAD

**Issue by zhoud2001** [teslamotors/vehicle-command#321]
It will let me erase all guest data but I cannot toggle my cars into Guest Mode.

**Comment by sethterashima** [comment]
How are you trying to enable Guest Mode? Can you provide debug logs (most SDK tools have a `-debug` flag).

**Comment by zhoud2001** [comment]
It’s just when I do Tesla-control -h and I do not see the documentation for enable guest mode mode at allSent from my iPhoneOn Oct 14, 2024, at 4:11 PM, sethterashima ***@***.***> wrote:﻿
How are you trying to enable Guest Mode? Can you provide debug logs (most SDK tools have a -debug flag)?
