### ISSUE TITLE
how to set the vehicle temperature ?

### ISSUE THREAD

**Issue by zhy2020** [teslamotors/vehicle-command#331]
Hello,

When I tried to set the vehicle temperature using the code below, the system returned an error. Could you please let me know if I used it incorrectly?

get return:

![image](https://github.com/user-attachments/assets/7456c879-fcaa-4167-8fb4-a3342451f921)

`
        UniversalMessage_Domain domain = UniversalMessage_Domain_DOMAIN_INFOTAINMENT;
        unsigned char message_buffer[260];
        size_t message_buffer_length = 0;
      
        changeClimateTemp(22.5, 20.5, message_buffer, &message_buffer_length);
        
        buildRoutableMessage(domain, message_buffer, message_buffer_length, output_message_buffer,
                             &output_message_buffer_size);
  
  // then send output_message_buffer by ble
  
      int changeClimateTemp(float driver_celsius, float passenger_celsius, unsigned char *buffer, size_t *buffer_size)
      {
              CarServer_HvacTemperatureAdjustmentAction hvacTemperatureAdjustmentAction = CarServer_HvacTemperatureAdjustmentAction_init_default;
              hvacTemperatureAdjustmentAction.driver_temp_celsius = driver_celsius;
              hvacTemperatureAdjustmentAction.passenger_temp_celsius = passenger_celsius;
              hvacTemperatureAdjustmentAction.has_level = true;
      
          CarServer_HvacTemperatureAdjustmentAction_Temperature hvacAdjustmentAction_Temperature = CarServer_HvacTemperatureAdjustmentAction_Temperature_init_default;
          hvacAdjustmentAction_Temperature.which_type = CarServer_HvacTemperatureAdjustmentAction_Temperature_TEMP_MAX_tag;
          hvacAdjustmentAction_Temperature.type.TEMP_MAX = (CarServer_Void){0};
      
          hvacTemperatureAdjustmentAction.level = hvacAdjustmentAction_Temperature;
      
          CarServer_VehicleAction vehicle_action = CarServer_VehicleAction_init_default;
          vehicle_action.which_vehicle_action_msg = CarServer_VehicleAction_hvacTemperatureAdjustmentAction_tag;
          vehicle_action.vehicle_action_msg.hvacTemperatureAdjustmentAction = hvacTemperatureAdjustmentAction;
      
          CarServer_Action car_server_action = CarServer_Action_init_default;
          car_server_action.action_msg.vehicleAction = vehicle_action;
          car_server_action.which_action_msg = CarServer_Action_vehicleAction_tag;
      
          return buildActionMessage(&car_server_action, buffer, buffer_size);
      }
  
  
    int buildActionMessage(CarServer_Action *car_server_action, unsigned char *buffer, size_t *buffer_size)
    {
          pb_ostream_t size_stream = PB_OSTREAM_SIZING;
          if (!pb_encode(&size_stream, CarServer_Action_fields, car_server_action))
          {
              NRF_LOG_INFO("Failed to encode message: %s", PB_GET_ERROR(&size_stream));
              return NANOPB_ENCODE_ERROR;
          }
    
        pb_ostream_t stream = pb_ostream_from_buffer(buffer, size_stream.bytes_written);
        if (!pb_encode(&stream, CarServer_Action_fields, car_server_action))
        {
            NRF_LOG_INFO("Failed to encode message: %s", PB_GET_ERROR(&stream));
            return NANOPB_ENCODE_ERROR;
        }
  
        *buffer_size = stream.bytes_written;
        return 0;
    }
`

**Comment by sethterashima** [comment]
I'd suggest following the instruction on how to [decode protobuf messages](https://github.com/teslamotors/vehicle-command/blob/main/pkg/protocol/protocol.md#decoding-messages) and compare the output of `tesla-control` to the output of your program. [Switching](https://github.com/teslamotors/vehicle-command/blob/main/pkg/connector/ble/ble.go#L51) the BLE to use AuthMethodHMAC instead of AuthMethodGCM will get the program to send unencrypted (but still signed) messages, which may make this easier.

Support for other implementations is beyond the scope of this issue tracker, but hope this helps.
