### ISSUE TITLE
TLS handshake errors running docker on the Azure

### ISSUE THREAD

**Issue by Kieran260** [teslamotors/vehicle-command#336]
Hi, if this isn't the right place for this question please direct me towards somebody who may be able to help!

We're using Azure container apps to host the container as a proxy, pulling it directly from docker hub and have all of the environment variables configured. The three keys are inside of the container and the container is running. We are running the exact same configuration locally and we're able to communicate via HTTPS, even from another machine on the LAN.

**Problem:** For the cloud hosted container when trying to access the proxy via https we're getting this error: Client sent an HTTP request to an HTTPS server. We've got the ingress set up to accept HTTPs only to port 443. 
![image](https://github.com/user-attachments/assets/f108dc42-fa55-40cd-9bf8-67148d0e01b2)

Is there something we're doing wrong here?
Thanks!

**Comment by Daeell** [comment]
Hi, I experienced a similar issue, did you solve it?

**Comment by Kieran260** [comment]
Hi, yes I discovered that the cloud service was terminating the requests at the edge into HTTP regardless of ingress settings. 

You could add a reverse proxy e.g. NGINX inside a container to forward a new HTTPs connection internally to the command proxy. 

There's possibly other easier ways but this is the most cost efficient for my project.
