### ISSUE TITLE
[Feature Request] Support for Specifying Homelink Device to Trigger

### ISSUE THREAD

**Issue by Bradez** [teslamotors/vehicle-command#4]
# Summary
The API currently allows you to [trigger homelink](https://developer.tesla.com/docs/fleet-api#trigger_homelink). However, it is possible to have multiple homelink devices attached to a single vehicle. There is no way to list or select which device to trigger from. It will, therefore, only trigger the first homelink device that was configured. This has been a long-time missing feature and disparity between API and vehicle.

# Feature Request
 - Allow retrieving a list of homelink devices configured for a given vehicle; and
 - Add a field to the `trigger_homelink` endpoint wherein a `homelink_device_id` can be supplied.

**Comment by sethterashima** [comment]
Closing as out of scope. Unfortunately I don't have the bandwidth for feature requests that would require vehicle firmware changes.
