### ISSUE TITLE
Installing Virtual Key for many vehicles at once

### ISSUE THREAD

**Issue by stx** [teslamotors/vehicle-command#41]
Is there a way to install a Virtual Key to all vehicles in an account, without manually visiting the link for every vehicle in the fleet? This is pretty onerous for businesses with hundreds of cars, as you'd expect.

**Comment by simon-norman** [comment]
Second this, the end-to-end security is great but the current flow is absolutely not practical for anyone with more than a few vehicles, especially if they have a mix of post-2021 and other vehicles

**Comment by sethterashima** [comment]
Unfortunately, remotely adding keys is incompatible with providing end-to-end authentication.
