### ISSUE TITLE
What are session best practices?

### ISSUE THREAD

**Issue by andig** [teslamotors/vehicle-command#48]
Sending commands to vehicle requires running session. A session can only be started if the vehicle is awake apparently. That seems to imply that sessions may be short-lived, i.e. should only be established as long as they are needed for running a command. It would be helpful it `Vehicle` had a method to identify if it has an established session.

Does an established session mean that the vehicle is kept awake?

It is also not clear if `Wakeup` requires a an established session or if wakeup requests even need by signed?

What are the best practices?

**Comment by jbanyer** [comment]
> It is also not clear if `Wakeup` requires a an established session or if wakeup requests even need by signed?

I have observed that `wake` commands are not signed by the proxy - they are forwarded directly the the API. They also always send the same reply, whether the vehicle is awake or not, and whether they work or not.

**Comment by andig** [comment]
@jbanyer OT: seems it would be nice to have a developers forum around the new API as we're all facing the same issues. Any idea if such exists?

**Comment by sethterashima** [comment]
- Establishing a session will not keep the vehicle awake.
- A session only expires when the infotainment system or vehicle security controller reboots. If a client attempts to use an expired session, the vehicle responds with a handshake message to start a new session. When this happens, the SDK automatically resets the session and reattempts the command.
- Wakeup requires a session over BLE but not over the Internet. (See https://github.com/teslamotors/vehicle-command/pull/54).

A client can save/road sessions from disk to save a round trip for the handshake. See https://pkg.go.dev/github.com/teslamotors/vehicle-command@v0.0.1/pkg/cache for more information.

**Comment by andig** [comment]
@sethterashima highly appreciated. Would be great to add that to the docs. I assume wakeup not needing a session also doesn‘t need it be signed?

**Comment by sethterashima** [comment]
Wakeup over the Internet does not need to be signed (since a sleeping car can't authenticate the command, this avoids a chicken-and-egg problem). Wakeup over BLE _does_ need to be signed (the vehicle security controller is always awake, and the command tells it to wake up the infotainment system).
