### ISSUE TITLE
[Document Request] Request to add ble specification document.

### ISSUE THREAD

**Issue by JSpiner** [teslamotors/vehicle-command#5]
I couldn't believe my eyes when I saw this great project that released the code to control a car with ble.
There is huge potential for use. Thank you very much.
I am curious if there are any plans to create a separate document for the specifications for controlling vehicles with BLE.
The devices on which Linux-based golang ble can run are limited.
It would be of great help if documentation was provided to support implementation on Android or iOS, which are used by many people.

**Comment by sheng168** [comment]
I have implemented an iOS BLE client base on information in this repo, running tesla-control -debug ...
and decoding the TX/RD hex dumps and reproducing them

**Comment by sethterashima** [comment]
https://github.com/teslamotors/vehicle-command/blob/main/pkg/protocol/protocol.md
