### ISSUE TITLE
rate limits are not currently applied

### ISSUE THREAD

**Issue by jbanyer** [teslamotors/vehicle-command#57]
The new API describes rate limits under the Discovery Plan.

However in my limited testing these rate limits don't seem to be applied currently. Specifically:
- one vehicle data per 5 minutes (I can send one call per minute)
- 50 commands per day per vehicle (I can send over 100 commands per day)

Is there a timeframe for implementing the rate limits?

**Comment by jbanyer** [comment]
Any chance of an update here?

We'd like to prepare for the rate limits before they become effective, but it's difficult without knowing exactly how they work.

For example, regarding the "vehicle data" 1 call per 5 minutes per vehicle limit. Currently we poll vehicles like this:
- `GET /api/1/vehicles` - check if the vehicle is awake / online
- if awake: `GET /api/1/vehicles/${id_s}/vehicle_data`

If the first call counts toward the rate limit, the second call would always fail.

Do we need to change this?

**Comment by ThomasAlxDmy** [comment]
We're currently giving free almost unlimited access. This will change in the next couple months.

**Comment by vbarrier** [comment]
Hi, is this issue #255 cancelled?
