### ISSUE TITLE
HTTP errors swallowed after retry by context deadline expired

### ISSUE THREAD

**Issue by morganofslo** [teslamotors/vehicle-command#69]
If a command to a vehicle fails with an HTTP error not already handled by the ShouldRetry() logic, it will retry in the dispatcher.  Eventually, after repeated failures the context deadline will timeout, and the code returns ctx.Err() in several places instead of the original error.   

This obscures the underlying error from the caller who may find the error more useful than 'context deadline exceeded'.

I discovered this because [the code in inet.go](https://github.com/teslamotors/vehicle-command/blob/main/pkg/connector/inet/inet.go#L111) does not properly handle a vehicle sleep 408 error {"response":null,"error":"vehicle is offline","error_description":""},  and instead retries until timeout.

**Comment by rawmean** [comment]
I think they fixed this in the patch that they made today. Please verify
