### ISSUE TITLE
"unsigned_cmds_hardlocked" message from new Fleet API

### ISSUE THREAD

**Issue by morganofslo** [teslamotors/vehicle-command#76]
Anyone else see this?  This was for a vehicle using the [new REST API](https://developer.tesla.com/docs/fleet-api#overview), not the old owner api.  I assume this means Tesla is feature flagging this vehicle to require signed commands via vehicle-command api ahead of the January launch?

`{'response': {'result': False, 'reason': 'unsigned_cmds_hardlocked'}}`

Just odd that it's different than the other error they have documented:
`"Tesla Vehicle Command Protocol required, please refer to the documentation here: https://developer.tesla.com/docs/fleet-api#2023-10-09-rest-api-vehicle-commands-endpoint-deprecation-warning (403)"`

**Comment by stx** [comment]
Yep.

**Comment by rawmean** [comment]
It must be one of those cars that have not used the owner-api in the past 30 days. According to their notice, those cars will be forced to use the new API

**Comment by ChogosuJacob** [comment]
Any solution for this error?
I just got my new M3P and heard about Tasker.
So I purchased Tasker and Bolt for Tesla already and it's not working. :(
