### ISSUE TITLE
Safety Score API is not documented

### ISSUE THREAD

**Issue by rawmean** [teslamotors/vehicle-command#91]
The old endpoint for Safety Score does not work for new cars anymore and the Fleet API does not document it.
old endpoint: `https://akamai-apigateway-vfx.tesla.com/safety-rating/daily-metrics?vin=<vin>&deviceCountry=US&deviceLanguage=en&timezone=America/Los_Angeles&appVersion=4.27.5&hasInsurance=true`

I get this response (401 http error):

```
{
    "message": "401 Unauthorized",
    "context": {
        "code": 401,
        "url": "http://vfx-insurance-mobile-burstapp-prod.tesla.com/safety-rating/daily-metrics?vin=5YJ3E1EC6PF513580&deviceCountry=US&deviceLanguage=en&timezone=America/Los_Angeles&appVersion=4.27.5&hasInsurance=true",
        "method": "get",
        "request": {
            "params": {
                "vin": "<vin>",
                "deviceCountry": "US",
                "deviceLanguage": "en",
                "timezone": "America/Los_Angeles",
                "appVersion": "4.27.5",
                "hasInsurance": "true"
            }
        },
        "source": {
            "type": "NotAuthenticatedException",
            "reason": "Invalid signature",
            "referenceNumber": "5YE1EC3580"
        }
    },
    "errorMessage": ""
}
```

**Comment by derekargueta** [comment]
The Safety Score API is not part of FleetAPI which is why it's not documented. We may be able to consider incorporating it into FleetAPI but that will require some internal discussion and design.

@sethterashima Let's close this one in favor of https://github.com/teslamotors/vehicle-command/issues/152
